# Generated by Django 3.0.5 on 2021-02-17 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('TestName', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('Students', models.IntegerField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Details',
            fields=[
                ('Rollno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('role', models.CharField(blank=True, choices=[('F', 'Faculty'), ('S', 'Student')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Session_Details',
            fields=[
                ('date', models.DateTimeField(default=datetime.datetime(2021, 2, 17, 16, 16, 46, 64849))),
                ('Session_Name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Branch', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('role', models.CharField(blank=True, choices=[('Q', 'Quiz'), ('L', 'Lab')], max_length=1)),
                ('NameOfTest', models.CharField(max_length=200)),
                ('QuizCreator', models.CharField(max_length=200)),
                ('QuizCreatorName', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'unique_together': {('Session_Name', 'NameOfTest')},
            },
        ),
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('rollno_test', models.CharField(max_length=210, primary_key=True, serialize=False)),
                ('rollno', models.CharField(editable=False, max_length=10)),
                ('test', models.CharField(max_length=200)),
                ('totalscore', models.FloatField()),
                ('securedscore', models.FloatField()),
                ('correct_answer', models.IntegerField()),
                ('wrong_answer', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'unique_together': {('rollno', 'test')},
            },
        ),
    ]
