# Generated by Django 3.0.5 on 2021-02-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Session_Name', models.CharField(max_length=200)),
                ('NameOfTest', models.CharField(max_length=200)),
                ('NumberOfQuestions', models.IntegerField(default=0)),
                ('Time', models.CharField(blank=True, default=0, max_length=100)),
                ('position', models.BooleanField(default=0)),
                ('slug', models.SlugField(unique=True)),
                ('ModeOfTime', models.CharField(max_length=200, null=True)),
            ],
            options={
                'unique_together': {('Session_Name', 'NameOfTest', 'NumberOfQuestions')},
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuizCreator', models.CharField(max_length=200)),
                ('QuizCreatorName', models.CharField(blank=True, max_length=200)),
                ('Session_Name', models.CharField(max_length=200)),
                ('NameOfTest', models.CharField(max_length=200)),
                ('Question', models.CharField(max_length=20000)),
                ('option1', models.CharField(blank=True, max_length=2000)),
                ('option2', models.CharField(blank=True, max_length=2000)),
                ('option3', models.CharField(blank=True, max_length=2000)),
                ('option4', models.CharField(blank=True, max_length=2000)),
                ('option5', models.CharField(blank=True, max_length=2000)),
                ('Answer', models.CharField(max_length=1)),
            ],
            options={
                'unique_together': {('Session_Name', 'NameOfTest', 'Question')},
            },
        ),
    ]
